In [15]:
#Importing Libraries
import numpy as np
import pandas as pd
import joblib
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
print('Libraries Imported')

Libraries Imported


In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


#load the team related datasets into the notebook and save them as dataframes
def country_df(csv):
  df = pd.read_csv(csv)
  df.sort_values('HomeTeam', inplace=True)
  df.reset_index(inplace=True)
  df.drop("index", axis =1 , inplace=True)

  return df

df_france = country_df('FootballData/F1.csv')
df_spain  = country_df('FootballData/SP1.csv')
df_england  = country_df('FootballData/E0.csv')
df_championship  = country_df('FootballData/E1.csv')
#df_finland  = country_df('/content/drive/MyDrive/FootballData/FIN.csv')
#df_germany = country_df('FootballData/D1.csv')
df_england_22 = country_df('FootballData/E0_22.csv')
df_spa_22 = country_df('FootballData/SP1_22.csv')
#df_jpn = country_df('FootballData/JPN.csv')
df_ita = country_df('FootballData/I1.csv')
df_E1 = country_df('FootballData/E1.csv')
df_E2 = country_df('FootballData/E2.csv')
df_E3 = country_df('FootballData/E3.csv')
df_EC = country_df('FootballData/EC.csv')
df_F2 = country_df('FootballData/F2.csv')
df_I2 = country_df('FootballData/I2.csv')
df_dataE0 = country_df('FootballData/data (9)/E0.csv')
df_dataE1 = country_df('FootballData/data (9)/E1.csv')
df_dataE2 = country_df('FootballData/data (9)/E2.csv')
df_dataE3 = country_df('FootballData/data (9)/E3.csv')
df_dataEC = country_df('FootballData/data (9)/EC.csv')
df_dataF2 = country_df('FootballData/data (9)/F2.csv')
df_dataG1 = country_df('FootballData/data (9)/G1.csv')
df_dataN1 = country_df('FootballData/data (9)/N1.csv')
df_dataP1 = country_df('FootballData/data (9)/P1.csv')
df_dataSC0 = country_df('FootballData/data (9)/SC0.csv')
df_dataSC1 = country_df('FootballData/data (9)/SC1.csv')
df_dataSC2 = country_df('FootballData/data (9)/SC2.csv')
df_dataSC3 = country_df('FootballData/data (9)/SC3.csv')
df_dataSP2 = country_df('FootballData/data (9)/SP2.csv')
df_dataSP1 = country_df('FootballData/data (9)/SP1.csv')
df_dataT1 = country_df('FootballData/data (9)/T1.csv')

df_data8E0 = country_df('FootballData/data (8)/E0.csv')
df_data8E1 = country_df('FootballData/data (8)/E1.csv')
df_data8E2 = country_df('FootballData/data (8)/E2.csv')
df_data8E3 = country_df('FootballData/data (8)/E3.csv')
df_data8EC = country_df('FootballData/data (8)/EC.csv')
#df_data8F2 = country_df('FootballData/data (8)/F2.csv')
df_data8G1 = country_df('FootballData/data (8)/G1.csv')
#df_data8N1 = country_df('FootballData/data (8)/N1.csv')
#df_data8P1 = country_df('FootballData/data (8)/P1.csv')
df_data8SC0 = country_df('FootballData/data (8)/SC0.csv')
df_data8SC1 = country_df('FootballData/data (8)/SC1.csv')
df_data8SC2 = country_df('FootballData/data (8)/SC2.csv')
df_data8SC3 = country_df('FootballData/data (8)/SC3.csv')
#df_data8SP2 = country_df('FootballData/data (8)/SP2.csv')
df_data8SP1 = country_df('FootballData/data (8)/SP1.csv')
df_data8T1 = country_df('FootballData/data (8)/T1.csv')


df_data7E0 = country_df('FootballData/data (7)/E0.csv')
df_data7E1 = country_df('FootballData/data (7)/E1.csv')
df_data7E2 = country_df('FootballData/data (7)/E2.csv')
df_data7E3 = country_df('FootballData/data (7)/E3.csv')
df_data7EC = country_df('FootballData/data (7)/EC.csv')
df_data7F2 = country_df('FootballData/data (7)/F2.csv')
df_data7G1 = country_df('FootballData/data (7)/G1.csv')
df_data7N1 = country_df('FootballData/data (7)/N1.csv')
df_data7P1 = country_df('FootballData/data (7)/P1.csv')
df_data7SC0 = country_df('FootballData/data (7)/SC0.csv')
df_data7SC1 = country_df('FootballData/data (7)/SC1.csv')
df_data7SC2 = country_df('FootballData/data (7)/SC2.csv')
df_data7SC3 = country_df('FootballData/data (7)/SC3.csv')
df_data7SP2 = country_df('FootballData/data (7)/SP2.csv')
df_data7SP1 = country_df('FootballData/data (7)/SP1.csv')
#df_data7T1 = country_df('FootballData/data (7)/T1.csv')




data = pd.concat([df_france, df_spain, df_england, df_championship, df_england_22, df_spa_22, df_ita,df_E1,df_E2,df_E3,df_EC,df_F2,df_I2,df_dataE0,df_dataE1,df_dataE2,df_dataE3,df_dataEC,df_dataF2,df_dataG1,df_dataN1,df_dataP1,df_dataSC0,df_dataSC1,df_dataSC2,df_dataSC3,df_dataSP1,df_dataSP2,df_dataT1,
                  df_data8E0,df_data8E1,df_data8E2,df_data8E3,df_data8EC,df_data8G1,df_data8SC0,df_data8SC1,df_data8SC2,df_data8SC3,df_data8SP1,df_data8T1,
                  df_data7E0,df_data7E1,df_data7E2,df_data7E3,df_data7EC,df_data7G1,df_data7SC0,df_data7SC1,df_data7SC2,df_data7SC3,df_data7SP1,df_data7SP2,df_data7P1,df_data7N1,df_data7F2], sort = False)

data.info()
data = data[["FTHG","FTAG","HST","AST","FTR"]]

#data['FTR'] = data['FTR'].map({'H':0,'D':1,'A':2})

# Create a boolean mask for rows with NaN values
mask = data.isnull().any(axis=1)

# Delete rows using the mask
data = data[~mask]

<class 'pandas.core.frame.DataFrame'>
Index: 21108 entries, 0 to 379
Columns: 139 entries, Div to BSA
dtypes: float64(129), int64(2), object(8)
memory usage: 22.5+ MB


In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14523 entries, 0 to 379
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   FTHG    14523 non-null  int64  
 1   FTAG    14523 non-null  int64  
 2   HST     14523 non-null  float64
 3   AST     14523 non-null  float64
 4   FTR     14523 non-null  object 
dtypes: float64(2), int64(2), object(1)
memory usage: 680.8+ KB


In [18]:
data.FTR.value_counts()

FTR
H    6456
A    4201
D    3866
Name: count, dtype: int64

In [19]:
data['FTR'].head()

0    A
1    H
2    H
3    D
4    H
Name: FTR, dtype: object

In [20]:
#Creating the dependent variable class
factor = pd.factorize(data['FTR'])
data.FTR = factor[0]
definitions = factor[1]
print(data.FTR.head())
print(definitions)

0    0
1    1
2    1
3    2
4    1
Name: FTR, dtype: int64
Index(['A', 'H', 'D'], dtype='object')


In [21]:
#Splitting the data into independent and dependent variables
X = data.iloc[:,0:4].values
y = data.iloc[:,4].values
print('The independent features set: ')
print(X[:4,:])
print('The dependent variable: ')
print(y[:4])

The independent features set: 
[[1. 3. 3. 4.]
 [1. 0. 2. 2.]
 [1. 0. 8. 3.]
 [0. 0. 7. 5.]]
The dependent variable: 
[0 1 1 2]


In [22]:
# Split the data to train and test dataset.
from sklearn.model_selection import train_test_split
sample_weight = np.random.RandomState(42).rand(y.shape[0])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.9,shuffle=True,random_state=42)

In [23]:
# Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [24]:
# Fitting Random Forest Classification to the Training set
classifier = RandomForestClassifier(n_estimators = 1294, criterion = 'entropy', random_state = 42, max_depth=3, max_features='sqrt')
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', max_depth=3, n_estimators=1294,
                       random_state=42)

In [25]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
#Reverse factorize (converting y_pred from 0s,1s and 2s to Home, Draw and Away wins
reversefactor = dict(zip(range(3),definitions))
y_test = np.vectorize(reversefactor.get)(y_test)
y_pred = np.vectorize(reversefactor.get)(y_pred)
# Making the Confusion Matrix
print(pd.crosstab(y_test, y_pred, rownames=['Actual Results'], colnames=['Predicted Results']))

Predicted Results     A     D     H
Actual Results                     
A                  3465   294    30
D                     0  3359   134
H                     0     0  5789


In [26]:
print(list(zip(data.columns[0:5], classifier.feature_importances_)))
joblib.dump(classifier, 'randomforestmodel.pkl') 

[('FTHG', 0.5018562167523986), ('FTAG', 0.4484169111385146), ('HST', 0.0236841453045679), ('AST', 0.026042726804519113)]


['randomforestmodel.pkl']

In [28]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# Load your trained RandomForestClassifier
model = joblib.load("randomforestmodel.pkl")

# Create a DataFrame with your single row of data
single_row = pd.DataFrame({
    'FTHG': [2.11],
    'FTAG': [3.88],
    'HS': [5.72],
    'AS': [4.02]
    
    # Add other features here...
})


# Predict using the model
predicted_class = model.predict(single_row)

# Reverse factorize the prediction
reversefactor = dict(zip(range(3), definitions))
predicted_label = reversefactor.get(predicted_class[0])

# Display the result
print(f"Predicted result: {predicted_label}")


Predicted result: H


c:\Users\USER\Wayne\Rolvaag\.venv\Lib\site-packages\sklearn\base.py:458: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
